### ISSUE TITLE
Please continue working

### ISSUE THREAD

**Issue by zeroby0** [joseqmatias/N1-Newton#1]
Hey, The theme is very nice, but there are alignment problems and other issues. Please continue working on the theme. I'll try to help you if required.  

Or as an alternative, we can fork Nylas Mail and customise it to make a fully functional Newton clone. I'd love to work with you on that as well.

Please let me know what you think
Thanks

Regards,
Aravind Reddy V.

**Comment by thematz** [comment]
Hi Aravind,

Thank you for you message and sorry for the very late reply. 

I will start working on this theme again. Soon I will have updates.

Regards,
Matias
